spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

import:
  html-file-location: classpath:import/helmes.html